[package]
name = "D88FileIO"
version = "0.0.1"
edition = "2021"
authors = ["ORYZAPAO <oryzapao@gmail.com>"]     w
edition = "2018"
repository = "https://github.com/ORYZAPAO/d88dmp"
keywords = [
         "d88","d88dmp"
]
license = "MIT"


[dependencies]
