[package]
name = "D88FileIO"
version = "0.0.2"
authors = ["ORYZAPAO <oryzapao@gmail.com>"]
edition = "2018"
repository = "https://github.com/ORYZAPAO/d88dmp"
keywords = [
         "d88","d88dmp"
]
license = "MIT"
description = "d88 File Access Lib."

[dependencies]
